### ISSUE TITLE
Why is MGI's gene2phenotype API not being called by BTE?

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#129]
In this notebook https://gist.github.com/andrewsu/c183b91118ba422d31aea9443c392ea3, I ask for Gene-to-PhenotypicFeature relationships.  BTE queries three APIs:

```
BTE found 3 apis:

API 1. ebi_gene2phenotype(1 API call)
API 2. biolink(2 API calls)
API 3. semmed_phenotype(13 API calls)
```

However, the SmartAPI metakg also lists a fourth API with edges of this type -- MGI's gene2phenotype API.  Is BTE somehow excluding this API (perhaps because it is dealing with mouse genes and phenotypes, which aren't relevant to my query)?  Or has the SmartAPI information not been added to BTE yet?

![image](https://user-images.githubusercontent.com/2635409/96542871-e518e200-1257-11eb-930c-a74f331af518.png)

**Comment by kevinxin90** [comment]
@andrewsu 
<img width="425" alt="Screen Shot 2020-10-20 at 9 35 07 AM" src="https://user-images.githubusercontent.com/10997542/96617634-b67f2380-12b8-11eb-8041-16e3d40d7b2b.png">



As shown above, MGIgene2phenotype API connects **PhenotypicFeature to Gene**. However, it only takes **MP** ids as input. 


<img width="616" alt="Screen Shot 2020-10-20 at 9 36 01 AM" src="https://user-images.githubusercontent.com/10997542/96617189-293bcf00-12b8-11eb-8238-d1001e17eebe.png">


And as shown above, the input from BTE hint module for **cough** doesn't include **MP** ids. When BTE consults SmartAPI for available APIs to use, it's considering both input type as well as id type. That's why this one is excluded.

**Comment by andrewsu** [comment]
perfect, thank you!
