### ISSUE TITLE
NCBIGENE works, NCBIGene does not

### ISSUE THREAD

**Issue by cbizon** [biothings/biothings_explorer#180]
This query:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "id": "NCBIGENE:1017",
                    "category": "biolink:Gene"
                },
                "n1": {
                    "category": "biolink:Pathway"
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
returns results, but if n0.id is instead "NCBIGene" then no results are returned.

There was an inadvertent change from NCBIGene to NCBIGENE in one version of the biolink model, but in the current version it's back to NCBIGene.

**Comment by andrewsu** [comment]
I believe this issue was fixed in https://github.com/biothings/BioThings_Explorer_TRAPI/pull/168.  Current behavior seems correct to me -- returns results for `NCBIGene` but not `NCBIGENE`.  Can you confirm and close the issue if it works for you?

also, for future reference, unless you know that an issue applies specifically to the python client (this repo), you should log issues in https://github.com/biothings/BioThings_Explorer_TRAPI. (Our fault -- we need to make it clearer in a few places...)

**Comment by cbizon** [comment]
Yes, looks fixed, thanks.
