### ISSUE TITLE
update predicates on startup, and on demand via API endpoint

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#194]
In #141, we put the update of `/data/predicates.json` and `/data/smartapi_specs.json` on a cron job that runs every 10 minutes (see `updateSmartAPISpecs` in https://github.com/biothings/BioThings_Explorer_TRAPI/blob/master/src/controllers/cron/update_local_smartapi.js#L138).  But the cron job will restart the server and interrupt any currently-running jobs, which will increasingly become an issue with long-running jobs.  A possibly better solution would be to run `updateSmartAPISpecs` on startup, create an API endpoint to trigger `updateSmartAPISpecs`, and reduce the cron frequency to a daily update.

**Comment by ericz1803** [comment]
After some investigation, any time one of the `v1` endpoints are hit, a new knowledge graph is generated. For example, for the `/v1/meta_knowledge_graph` route, it calls the [`getKG`](https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/routes/v1/meta_knowledge_graph_v1.js#L8) function, which creates a new knowledge graph (See https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/controllers/meta_knowledge_graph.js#L18-L20 and https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/controllers/meta_knowledge_graph.js#L61)

(The other paths seem the same. See https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/src/controllers/predicates.js#L54, https://github.com/biothings/bte_trapi_query_graph_handler/blob/main/src/index.js#L95)

Because of this, it seems unnecessary to restart the server any time `predicates.json` or `smartapi_specs.json` is updated. The problem of the cron job restarting the server and interrupting jobs can be solved by replacing the `npm start` script with `node src/server.js` (or `nodemon --ignore './data/' src/server.js` as Andrew suggested if nodemon is still needed).

- Are there any problems that could be caused by not restarting the server after updating these files?
- Could any problems be caused by updating the specs while a query is running?
- Are there any other parts of the code that 

Insights from someone who knows the repo better appreciated!

**Comment by newgene** [comment]
@ericz1803 on production bte server, we run `node src/server.js` directly, so no server restart when two smartapi data files are updated. Here in `package.json` file, it will be just up to how people use `npm start` in their development flow. I typically just use `npm run debug` on my local which will auto-restart with debug logs turned on.

**Comment by newgene** [comment]
And I agree with @andrewsu, a daily refresh should be good enough.
