### ISSUE TITLE
Support for ontology-based node expansion from the input query graph

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#196]
Expand node by its id, e.g. if user provides a MONDO ID as input, we will traverse MONDO hierarchy to get all its descendants.

This will depend on an ontology API to get the descendants of the given node, e.g. a biothings API or SRI's ontology service.

**Comment by newgene** [comment]
This is a specific issue as part of #92, also related to the predicate expansion issue #167

**Comment by newgene** [comment]
Per Kevin, "Can add query graph expansion here: https://github.com/biothings/bte_trapi_query_graph_handler/blob/018bc2fd0b7a1f2a230069b4fecd57841739944e/src/query_graph.js#L86" (after the validation step)

**Comment by andrewsu** [comment]
some descriptions of the desired behavior is described in this PR https://github.com/NCATSTranslator/TranslatorArchitecture/pull/60

**Comment by colleenXu** [comment]
In the generalize_query_handling branch (currently this [PR](https://github.com/biothings/bte_trapi_query_graph_handler/pull/35)), we currently remove the sub-entity expansion that is automatically done from the COHD (TRAPI v1.1) endpoint. 

We may need to revert that commit and work with that code in the future to support this. It's in bte_trapi_query_graph_handler; with the ID 490dd6f (full hash 490dd6fb70dd60f55114dbde2b8f420c503e7ff7) 

---

Background: 

This is because we encountered issues when the KP does subentity-expansion. It will then return edges linked to IDs that aren't the ID it was queried with (like returning links to subclasses of a Disease). The PR's body of code cannot parse this correctly and treats it as an "undefined or empty record" (Slack discussion [here](https://suwulab.slack.com/archives/CC218TEKC/p1630347237121300?thread_ts=1630346873.119600&cid=CC218TEKC))

The commit mentioned above removes those wonky records, which then means we've removed the subentity-expansion work done by a KP like COHD...

**Comment by colleenXu** [comment]
note: I don't notice a entity-based expansion (ontology or otherwise) from COHD TRAPI v1.2's default behavior. I also don't see any issues with BTE ingesting it. 

I therefore added a commit to add cohd back into the list of apis we query: https://github.com/biothings/BioThings_Explorer_TRAPI/commit/23308b8a50f8cbe127bdca779971557cd334b8dd

example: POST to https://cohd.io/api/query (diseases related to asthma)
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["MONDO:0004766"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

**Comment by andrewsu** [comment]
Note that the desired behavior is spelled out in point 9i of https://github.com/NCATSTranslator/TranslatorArchitecture/blob/master/README.md:
> 9. KPs that implement the Translator Reasoner API must perform the following kinds of reasoning in answering queries:
>     i. Making identifiers more specific, e.g. responding to a query involving an entity with information related to a subclass of that entity. In the knowledge_graph portion of the response, the more-specific identifier must be present and linked to the less-specific identifier. In the results portion of the response, the more-specific response node will be bound to the less-specific query node.

Another clear example of where BTE is not performing this operation as intended is https://github.com/NCATSTranslator/testing/issues/203.

**Comment by colleenXu** [comment]
The linked standup queries (https://github.com/NCATSTranslator/testing/issues/203 and https://github.com/NCATSTranslator/testing/issues/207) use this query, which I modified to make it easier for me to read

<details>

<summary>SmallMolecule -(does stuff to)-> abnormal blood glucose concentration</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:treats",
                        "biolink:disrupts",
                        "biolink:prevents",
                        "biolink:affects"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "categories": ["biolink:SmallMolecule"]
                },
                "n01": {
                    "ids": ["HP:0011015"],
                    "categories": ["biolink:PhenotypicFeature"]
                }
            }
        }
    }
}
```

</details>

Using the current PRs https://github.com/biothings/bte-trapi-workspace/pull/17 and https://github.com/biothings/bte_trapi_query_graph_handler/pull/113:

The console logs show that the HP term was expanded to include its descendants
```
  bte:biothings-explorer-trapi:main Expanded ids for node n01: (1 ids -> 14 ids) +0ms
```

We end up getting 2733 results in 53 s (12.3 MB). 
![Screen Shot 2022-09-22 at 1 43 18 PM](https://user-images.githubusercontent.com/43731687/191847315-6921bd11-7f59-4f1c-9943-71fd8174cba6.png)

With results like this (SmallMolecule connected to a descendant ID of the original QNode ID):
![Screen Shot 2022-09-22 at 1 44 13 PM](https://user-images.githubusercontent.com/43731687/191847462-f01537c3-af7f-4896-b8e8-446e66e9610e.png)

---

Note that if `is_set: True` is added to the QNodes that expand IDs, you get 2102 results and I find it easier because 1 result will contain all the IDs involved in the expansion that are connected to the rest of the sub-graph. 

<details>
<summary>modified query</summary>

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01",
                    "predicates": [
                        "biolink:treats",
                        "biolink:disrupts",
                        "biolink:prevents",
                        "biolink:affects"
                    ]
                }
            },
            "nodes": {
                "n00": {
                    "categories": ["biolink:SmallMolecule"]
                },
                "n01": {
                    "ids": ["HP:0011015"],
                    "categories": ["biolink:PhenotypicFeature"],
                    "is_set": true
                }
            }
        }
    }
}
```
</details>

Example of result:
![Screen Shot 2022-09-22 at 1 48 00 PM](https://user-images.githubusercontent.com/43731687/191848138-388b2025-6f4b-40da-a6d4-be83c2003c67.png)

**Comment by colleenXu** [comment]
This is a 1-hop Predict, vs https://github.com/biothings/BioThings_Explorer_TRAPI/issues/366 which is an Explain style query with 1 intermediate.

**Comment by colleenXu** [comment]
Jackson says the related PRs have been pushed to ITRB Prod instances, so we can close these issues https://github.com/biothings/BioThings_Explorer_TRAPI/issues/497#issuecomment-1404139480
