### ISSUE TITLE
annotate mychem.info fda_adverse_event mapping to "biolink:causes_adverse_event"

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#217]
mychem reports adverse event data from FAERS (through drug central).  For example: https://mychem.info/v1/query?q=drugbank.name:nitisinone&fields=drugcentral.fda_adverse_event

```
{
    "took": 4,
    "total": 1,
    "max_score": 8.669861,
    "hits": [
        {
            "_id": "OUBCNLGXQFSTLU-UHFFFAOYSA-N",
            "_score": 8.669861,
            "drugcentral": {
                "_license": "http://bit.ly/2SeEhUy",
                "fda_adverse_event": [
                    {
                        "drug_ae": 5,
                        "drug_no_ae": 142,
                        "level": "PT",
                        "llr": 11.1531004639185,
                        "llr_threshold": 94.8398736756999,
                        "meddra_code": 10040047,
                        "meddra_term": "Sepsis",
                        "no_drug_ae": 32368,
                        "no_drug_no_ar": 3353344
                    },

...
```

We should add an edge in the mychem openapi file (https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mychem.info/openapi_full.yml) that links `ChemicalSubstance` to `DiseaseOrPhenotypicFeature` using the predicate `biolink:causes_adverse_event`. 

Prompted by this Translator standup query: https://github.com/NCATSTranslator/testing/issues/82

**Comment by colleenXu** [comment]
My understanding is that we try NOT to map to those higher biolink entity classes. 

I would suggest using PhenotypicFeature (or maybe Disease) rather than DiseaseOrPhenotypicFeature. With the example link above, most things look like PhenotypicFeatures (one exception is Hepatocellular carcinoma).

For the operation above, the IDs are names (ChemicalSubstances) and MEDDRA (PhenotypicFeatures?). Perhaps we should use something else for ChemicalSubstances (other drugcentral-based operations are using CHEMBL.COMPOUND ids)? There are MEDDRA mappings for PhenotypicFeature in the [biomedical id resolver config file](https://github.com/biothings/biomedical_id_resolver.js/blob/09c070624c5e1ad16515a42c67b3976d9a12799f/src/config.ts#L179) currently....and I added Disease MEDDRA mappings in this PR: https://github.com/biothings/biomedical_id_resolver.js/pull/61

**Comment by andrewsu** [comment]
The commit to add `x-bte-kgs-operations/causesAdverseEvent` and `x-bte-kgs-operations/adverseEventCausedBy` in https://github.com/NCATS-Tangerine/translator-api-registry/commit/9155bf80aa28d62c9c276a5788bbb38dc648993a looks good to me. The use of Phenotypic Feature instead of DiseaseOrPhenotypicFeature sounds good to me.  Do we also _need_ to add MEDDRA as a Disease ID (https://github.com/biothings/biomedical_id_resolver.js/pull/61/commits/4d4e1ad01b7a68f523b80ad1504477f8a1ff0458), or can we treat all MEDDRA IDs as Phenotypic Features only?

**Comment by colleenXu** [comment]
TDLR: deciding to map MEDDRA IDs to Disease semantic type right now, since 

1. we have the most mapping support for it in MyDisease right now
2. this will likely be useful for use cases (doing another hop from the Disease to treatments like chemicals, for instance)

---

Comparing the xrefs to MEDDRA that we have right now:

- MyDisease.info has 1396 records with [mondo.xrefs.meddra](https://mydisease.info/v1/query?q=_exists_:%22mondo.xrefs.meddra%22), and 34 records with [disease_ontology.xrefs.meddra](https://mydisease.info/v1/query?q=_exists_:%22disease_ontology.xrefs.meddra%22)
- the biothing hpo api has 93 records with [xrefs.meddra](https://biothings.ncats.io/hpo/query?q=_exists_:%22xrefs.meddra%22)

**Comment by colleenXu** [comment]
How to find examples to test BTE with:

1. Look at MyDisease for records with [the meddra xrefs](https://mydisease.info/v1/query?q=_exists_:%22mondo.xrefs.meddra%22%20OR%20_exists_:%22disease_ontology.xrefs.meddra%22)
2. Query MyChem for records with the meddra code like [this](https://mychem.info/v1/query?q=drugcentral.fda_adverse_event.meddra_code:10001052&fields=drugcentral.fda_adverse_event,drugcentral.synonyms). If you return results, then these can be used as examples. 

Some associations that we can expect to retrieve:
- Disease acute respiratory distress syndrome (MEDDRA:10001052) <-> ChemicalSubstance neulasta (CHEMBL.COMPOUND:CHEMBL1201568)
- Disease angioimmunoblastic T-cell lymphoma (MEDDRA:10002449) <-> ChemicalSubstance brentuximab vedotin (CHEMBL.COMPOUND:CHEMBL1742994)
- Disease Clostridium difficile colitis (MEDDRA:10009657) <-> ChemicalSubstance nivestim (CHEMBL.COMPOUND:CHEMBL1201567)

**Comment by andrewsu** [comment]
I didn't do a live test, but these changes look like they address the intent and desired behavior describe in this issue...

**Comment by colleenXu** [comment]
[edit: Fix was to use drugcentral.xrefs.chembl_id (1994 / 2016 of the drugcentral adverse event records also have this field]

The operation for Chemical -> Disease will sometimes encounter issues with ID resolving the chemical. 

There are 2016 records with [drugcentral adverse event info](https://mychem.info/v1/query?q=_exists_:drugcentral.fda_adverse_event), and [1768 of them](https://mychem.info/v1/query?q=_exists_:drugcentral.fda_adverse_event%20AND%20_exists_:chembl.molecule_chembl_id) also have chembl.molecule_chembl_id. This leaves [248 records](https://mychem.info/v1/query?q=_exists_:drugcentral.fda_adverse_event%20AND%20NOT%20_exists_:chembl.molecule_chembl_id) that don't have the chembl field; however, their _id does seem to be CHEMBL.COMPOUND.

For Disease -> Chemical, I can handle this by changing the scope of the mychem query (to have  "_id,chembl.molecule_chembl_id"). 

But for Chemical -> Disease, I can only give one field for the output ID mapping...so I'll do chembl.molecule_chembl_id since more records will have this.

**Comment by colleenXu** [comment]
Should be addressed, since both PRs are merged now.
