### ISSUE TITLE
add COHD as a data source

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#223]
Issue to track integration of COHD as a data source for BTE.

smartAPI record: https://smart-api.info/registry?q=70117385218edc9bc01633829011dfcf
related standup query: https://github.com/NCATSTranslator/testing/issues/88

I'm guessing the primary issue is adding OMOP as a valid identifier in our various ID resolution services...

**Comment by colleenXu** [comment]
We can ingest the COHD TRAPI v1.1 now through TRAPI meta_knowledge_graph. I'm going to make a commit to do so. 

We can handle the API's edge attributes once we merge Eric Zhou's ICEES-related PRs around edge attributes...

I've noted potential issues with ingesting the COHD TRAPI v1.2 APIs [here](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/248#issuecomment-907541227).

**Comment by colleenXu** [comment]
note: I don't notice a entity-based expansion (ontology or otherwise) from COHD TRAPI v1.2's default behavior.

I therefore added a commit to add cohd back into the list of apis we query: https://github.com/biothings/BioThings_Explorer_TRAPI/commit/23308b8a50f8cbe127bdca779971557cd334b8dd

example: POST to https://cohd.io/api/query (diseases related to asthma)
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["MONDO:0004766"]
                },
                "n1": {
                    "categories": ["biolink:Disease"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
