### ISSUE TITLE
Add TRAPI version to Text Mining Provider endpoint URLs

### ISSUE THREAD

**Issue by bill-baumgartner** [biothings/biothings_explorer#228]
Hi BTE,

As mentioned during the Architecture call today (7/27), it is recommended practice to include the TRAPI version as part of a TRAPI endpoint URL. This issue is simply a request to add the TRAPI version to the Text Mining Provider endpoint URLs if possible. Thanks!

**Comment by andrewsu** [comment]
@bill-baumgartner because adding the TRAPI version number might imply that we will be supporting and maintaining older minor versions, and because we're not ready to commit to supporting multiple versions of each endpoint, we are planning on tabling this ticket until a later time (perhaps after the December demo).  Does that sound reasonable?

**Comment by bill-baumgartner** [comment]
Sounds good to me @andrewsu. Thanks!

**Comment by colleenXu** [comment]
Sorry for the closing / reopening issue confusion. I think this issue can either be kept open but "dormant" for now, or can be closed. @andrewsu can make that choice...

**Comment by andrewsu** [comment]
closing since current solution has TRAPI version in SmartAPI annotation
