### ISSUE TITLE
investigate use of ARAX NGD service for results scores

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#232]
related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/201

**Comment by andrewsu** [comment]
Since we don't consider this to be a promising avenue for implementing ranking at the moment, closing this ticket...

**Comment by ericz1803** [comment]
The problems connecting the BTE TRAPI output to the ARAX NGD service were fixed in https://github.com/RTXteam/RTX/issues/1634 so it might be worth considering using it for scoring. 

**How the ARAX NGD scores were retrieved**
The output from querying `https://api.bte.ncats.io/v1/query` was sent to `https://arax.ncats.io/api/arax/v1.2/query` with the `workflow` field changed to 
```json
  "workflow":[
      {
         "id":"overlay_compute_ngd",
         "parameters":{
            "qnode_keys":[
               "n0",
               "n1"
            ],
            "virtual_relation_label":"NGD"
         }
      }
   ]
```
Instead of being part of the `results` section, ARAX NGD scores are added under the `knowledge_graph` `edges` section of the response.

**How good are the NGD Results?**
Below is a comparison of ARAX NGD and the current BTE SEMMED where "zero scores" means that it returned a 0/inf score for an edge(ARAX) or result (BTE) and "nonzero scores" means the opposite.

<details><summary>Query 1</summary>
<p>

```json
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["MONDO:0005737"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n1",
                    "object": "n0"
                }
            }
        }
    }
}
```

<p>
</details>

**ARAX** 
ARAX nonzero scores: 169
ARAX zero scores: 89
**BTE SEMMED**
SEMMED nonzero scores: 12
SEMMED zero scores: 246

<details><summary>Query 2</summary>
<p>

```json
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "PUBCHEM.COMPOUND:5877", 
                        "PUBCHEM.COMPOUND:124653", 
                        "PUBCHEM.COMPOUND:6741"
                    ],
                    "categories": ["biolink:ChemicalEntity"]
                },
                "n1": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats", "biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```

<p>
</details>

**ARAX** 
ARAX nonzero scores: 886
ARAX zero scores: 311
**BTE SEMMED**
SEMMED nonzero scores: 0
SEMMED zero scores: 1197


<details><summary>Query 3 (two-hop)</summary>
<p>

```json
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["MONDO:0019188"]
                },
                "n1": {
                    "categories": ["biolink:ChemicalEntity"]
                },
                "n2": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e02": {
                    "subject": "n1",
                    "object": "n2"
                }
            }
        }
    }
}
```

<p>
</details>

This is a two-hop query so the qnode_keys specified in the workflow were `n0`, `n1`, and `n2`. The difference in number of results is because ARAX scores per edge while the results scores combine scores from multiple edges into a single score.
**ARAX**
ARAX nonzero scores: 1264
ARAX zero scores: 1703
**BTE SEMMED**
SEMMED nonzero scores: 413
SEMMED zero scores: 50
