### ISSUE TITLE
allow BTE to load a specific revision of the API metadata when specified

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_explorer#233]
By default, smartapi-kg package loads the latest API metadata from SmartAPI registry. It would be very useful if we can specify a github revision of this API metadata (only when the registered API metadata is hosted on github.com).

For example, if we can specific in a BTE config:

```
SMARTAPI_METADATA_REVISIONS = {
    // load a specific API Metadata for MyGene.info API 
    "59dce17363dce279d389100834e43648": "b43473b851b51596971da9067bcd9f9750250862"
}
```

**Comment by newgene** [comment]
An even more flexible option is to allow any URL to overwrite the existing SmartAPI metadata, should be very useful for the testing (e.g. using a version from a forked repo):

```
<smartapi_id>: <URL>
```

And even better, if the underline URL request package supports localfile-based URI (e.g. `file:///...`), we can load a temp API Metadata locally.

**Comment by colleenXu** [comment]
Note that this is more convenient compared to using the test/query endpoint, since multiple API YAMLs can be tested at once and it can be loaded from a url or local file in YAML format. 

The test/query endpoint has these limitations that made it hard to test YAMLs during the biolink v2.1 conversion:
- can only test 1 API's SmartAPI yaml/json at a time
- it has to be saved into a particular file / file location (smartapi.json in the test folder of bte-trapi)
- it has to be in a particular JSON format (involves conversion since we write in yaml, and some annoying copy-paste that sometimes doesn't work as expected)

**Comment by newgene** [comment]
Reopen this issue, as I noticed the absolute file path using the standard `file://` URI does not work. 

This is an example I used:

```
{
  "conf": {
    "only_overrides": false
  },
  "apis": {
    "adf20dd6ff23dfe18e8e012bde686e31": "file:///home/cwu/prj2/bte/workspace/packages/@biothings-explorer/bte-trapi/src/config/test_api_metadata.yml"
  }
}
```
Using the absolute file path allows us to put test metadata file anywhere.

**Comment by tokebe** [comment]
@newgene There are two problems here:

1. A typo on my part preventing paths being resolved properly
2. As we discussed [here](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/257#discussion_r693194404), `file:///` URIs are supposed to resolve to the `bte-trapi/data` folder as a root directory, rather than expecting an absolute path (or they would, if not for the aforementioned typo). Should I change this behavior so they expect an absolute path as well?

I'll await your decision before pushing changes/making a new PR.

**Comment by newgene** [comment]
:+1: @tokebe I noticed that `file://` URI can be either relative or absolute. Absolute URI starts with `file:///` (starts with `/`). It's good to use `data` folder as the base for relative path, but we might just support the absolute path as well if it's not too much trouble to add.

**Comment by tokebe** [comment]
@newgene The `url` package doesn't support `file://path/to/file`, so all file URIs must start with `file:///`, which the `url` package always converts into a path that `path.isAbsolute()` considers to be 'absolute'.

Considering that we already support local absolute paths by just entering an absolute path without `file:///` at the front, this seems like more work than it's worth, unless there's a specific reason to support both functions for file URIs specifically when the functionality is covered by regular path strings.

**Comment by newgene** [comment]
Agree. Then only absolute path it is, which should cover any local file use case. Relative `file://` support was suggested only if you want to keep the existing behavior since you have it implemented, but it looks like it's not worth anymore.

**Comment by tokebe** [comment]
Ok, made `file:///` use absolute paths rather than relative to the data folder.
