### ISSUE TITLE
Inconsistent behavior of `intermediate_nodes` 

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#25]
This code snippet linking an entity to an entity class:
```
fc = FindConnection(input_obj=cxcr4, output_obj='ChemicalSubstance', intermediate_nodes=None)
fc.connect(verbose=True)
```
results in this query summary: 
```
==========
========== QUERY PARAMETER SUMMARY ==========
==========

BTE will find paths that join 'CXCR4' and 'ChemicalSubstance'. Paths will have 0 intermediate node.
```

Whereas this similar query linking two entities:
```
fc = FindConnection(input_obj=asthma, output_obj=imatinib, intermediate_nodes=None)
fc.connect(verbose=True)
```
results in this query summary:
```
==========
========== QUERY PARAMETER SUMMARY ==========
==========

BTE will find paths that join 'asthma' and 'IMATINIB'. Paths will have 1 intermediate node.

Intermediate node #1 will have these type constraints: None
```
Both use `intermediate_nodes=None`, but the first query interprets that as looking for a direct connection (no intermediate nodes), whereas the second query interprets that as looking for one intermediate node with no type constraints.

**Comment by kevinxin90** [comment]
@andrewsu I see the issue here.
In the design, when user pass in a specific bio-entity as output_obj, e.g. 'IMATINIB' into BTE, we're going to trigger the "explain" feature of BTE.

And the design of the “explain" feature is to find **intermediate node(s)** which can connect the input and output (in order words, it assumes there is an intermediate node(s)). So even if the user pass in "None", we treat it as [None].

But that raise the issue here, which is inconsistency as you mentioned.

Are you suggesting if the user pass "None" as the value for intermediate_nodes, the query becomes "are there any direct associations between 'asthma' and 'imatinib'".

**Comment by andrewsu** [comment]
> Are you suggesting if the user pass "None" as the value for intermediate_nodes, the query becomes "are there any direct associations between 'asthma' and 'imatinib'".

Right, that was the behavior I was expecting.  Do you see any issues with changing that behavior (either in the design or the implementation)?

**Comment by kevinxin90** [comment]
Yes. There will be changes. Especially for the "verbose" mode. E.g we found "{num}" of intermediate nodes connecting from {input} to {output}".
That's going to be changed to "We (didn't) found connection between {input} and {output}".
But that's very small changes I can handle easily.

**Comment by andrewsu** [comment]
addressed in https://github.com/biothings/biothings_explorer/compare/dee12abe4472...66b73f1122d3
