### ISSUE TITLE
create user-friendly log for the TRAPI output

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#328]
Currently, the TRAPI response contains a very verbose "log" object. That log is not very useful for most BTE users, but very useful for developers and experts to debug. In https://github.com/biothings/BioThings_Explorer_TRAPI/issues/304, we will change behavior so that verbose log can be retrieve on demand, leaving the `log` field in the TRAPI output to be empty (except for a link to the verbose log).  In this ticket, we want to design and create a new "log" object for inclusion in the TRAPI output that is a more user-friendly summary of the BTE execution.

**Comment by colleenXu** [comment]
This issue is to discuss and plan our approach. Later we may make a post w/ a checklist + open issues to tackle each bite-sized task. 

I'm tagging others @andrewsu @newgene @tokebe @marcodarko @ariutta @ericz1803 so we can discuss what logs are actually useful and where those go.

My categories are:
* Logs to keep in the TRAPI response for users / helping devs understand issues w/o needing to login to BTE's server or see a console
* Console logs only for local dev troubleshooting / exploratory code

**Comment by colleenXu** [comment]
### My thoughts

Use [consistent language](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/379) to describe what's happening in logs, which isn't happening right now... 

#### Logs to keep in the TRAPI response

* A summary of the overall execution process:
    * What was the order of execution for QEdges? What QEdges were reversed?
* A summary of the response, similar to ARAX?
![Screen Shot 2021-12-22 at 3 56 00 PM](https://user-images.githubusercontent.com/43731687/147168034-235ba801-236e-4b7c-86da-ca35958bcbf9.png)
    * Number of nodes / edges in the knowledge-graph
    * Number of results in the results section
    * Number of unique sources (involves pulling edge-property provenance info)
        * Maybe listing them out?
        * Or instead the number of APIs w/ data in the response?
* List of APIs that are unavailable when the query is executed
    * These are APIs in our config file. But when the cron job is run, we sometimes fail to get the /meta_knowledge_graph response. Therefore our predicates file should lack that API's operations
* A summary of sub-query failure: useful info for us to adjust timeout / size of batch / figure out downstream API issues
    * Probably one for each QEdge?
    * For each failure: 
        * What API? 
        What was the operation (subject semantic type, predicate, object semantic type)?
        How many input IDs
        What was the failure? Often the 50-sec timeout was exceeded
* Asyncquery's internal job ID - [already implemented](https://github.com/biothings/BioThings_Explorer_TRAPI/pull/371)

---

#### Console logs (only for local dev troubleshooting)

* Removing logs from the query-builder that look like this? And considering whether to remove the log listing each query - since these are cut-off when the query is long anyways... 
```
  bte:call-apis:query {
  bte:call-apis:query   url: 'https://automat.renci.org/ctd/1.2/query',
  bte:call-apis:query   data: { message: { query_graph: [Object] }, submitter: 'infores:bte' },
  bte:call-apis:query   method: 'post',
  bte:call-apis:query   timeout: 50000,
  bte:call-apis:query   headers: { 'Content-Type': 'application/json' }
  bte:call-apis:query } +1ms
```
* Logs that make it clear when the workflow moves from 1 module to another, and what data is being handed off (its structure / format?)
* Making the logs at the end of a hop's execution easier to understand / summarized:
    * What is happening to curies + records (  `biothings-explorer-trapi:UpdatedExeEdge`,NewQNode, and edge-manager)? It looks like an iteration is happening through the QEdges until no more revisions happen, but it's not clear to me what is happening and why…

**Comment by tokebe** [comment]
@andrewsu @colleenXu Given that our TRAPI log responses have to conform to the [TRAPI logEntry standard](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/docs/reference.md#logentry-), which is used in ARAX to separate out different log levels, I think it might make sense to flip this problem slightly on its head.

Instead of returning a sort of execution summary and providing an endpoint to retrieve verbose logs as in #304, we may wish to instead return verbose logs by default as we currently do, and provide an endpoint to retrieve an execution summary, which we can link to in our verbose logs (similarly to how we provide the link to check the job status)?

Either way, I'm working on trying to come up with some standardized information structure we can side-load into our internal logEntry object to use for easily generating this summary based on the above desired info, will follow up with that when it's complete.

**Comment by colleenXu** [comment]
I'm not clear on what the LogEntry is meant to be used for, from the TRAPI team / Translator consortium perspective.... It certainly seems like other teams don't put as much info there as we do...

**Comment by newgene** [comment]
Things I think we can put into TRAPI logs (per discussion at our meeting):

* The actual KG edges process (summarized in [@colleenXu 's comment above](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/328#issuecomment-999944338))
* Errors during the above process (fail to call an API, to do id normalization etc)
* Execution summary at the end for a success run
* Possible other required log msgs decided by the TRAPI standard

If needed, we can also potentially put some logs (e.g. execution summary?) as a link in the TRAPI log entry, just for the purpose of reducing the log size.

**Comment by colleenXu** [comment]
notes from 1/5 meeting: 
* Jackson said we could use the LogLevel part of TRAPI LogEntry better: organize them into info/debug/error/warning, which ARAX organizes in its display. 
* we are discussing a change to what we put into the TRAPI Logs vs elsewhere. We are generally talking about reducing the amount of TRAPI logs we currently make + changing the logs we do make (console / TRAPI) to be more useful

* Jackson mentioned bull logging which is something separate as well...
* Chunlei mentioned "progress" status. as something nice but not necessary

* Err....what are the set of strings for the [code](https://github.com/NCATSTranslator/ReasonerAPI/blob/96fc1ead0746bcfcd8007c475db8bd015a499199/TranslatorReasonerAPI.yaml#L361) part of TRAPI LogEntry?

**Comment by tokebe** [comment]
Some further ideas:

- The TRAPI standard specifies `log_level` as part of a TRAPI query, implying that it's up to the user to decide the verbosity of the logs they receive
- This in mind, we could keep the majority of current logs as `DEBUG` level, and set new summaries as `INFO`
- We could then create summaries wherever appropriate, or at the end of execution, and they would be substantially easier to read on ARAX, or to filter for looking through raw JSON.

**Comment by tokebe** [comment]
@colleenXu I'm not sure if it's for the better to reduce the number of TRAPI logs we return...as it is they're a very good minimal set for decently detailed debugging without being too large. 

With a reduction of size for some of these logs (such as query success/failure logs) I'm thinking the best way to handle this is to keep `INFO`-level logs at a minimum and use those to give the user an at-a-glance as described above, and keep the rest just at the `DEBUG` level. 

Essentially, instead of creating a specifically placed 'summary' section of logs, a summary may be obtained by filtering out debug-level logs. This should be sufficiently sorted simply by execution order, e.g. edge execution order is given just by the order of `INFO` logs stating the current edge and if it's reversed. 

Given how scattered about a lot of the logs are in the code this is also probably the easiest plan to implement. Your thoughts?

**Comment by colleenXu** [comment]
I think this could be a good solution.

However, I wonder if we still want to review / edit the current logs. I've found some of the TRAPI logs unhelpful or confusing, hence #379 and some discussion on how to make some things clearer like edge execution order / reversing and switching from 1 module to another...

**Comment by tokebe** [comment]
@colleenXu Agreed, a general pass to make all logs more clear/useful is also in order and I'll be doing what I can there. Once I have a PR submitted it can be tested/reviewed for further worthwhile changes.

**Comment by colleenXu** [comment]
in our talk today @tokebe, we discussed next steps (after Jackson's first iteration). This would likely involve discussions with the whole teams and other devs' involvement:
* discussing #379 and getting a standard for this team to use
* reviewing the TRAPI log statements and making them useful / clear (might involve editing the underlying console logs)


We saw that there are a LOT of console log statements, and a step-wise approach would likely work best there (rather than reviewing all of them at once). For example:
* @marcodarko reviewing the edge-handling logs (console/TRAPI) and making them easier to understand. For example, why are we iterating through the edges multiple times? During an intersection, what node and edges are involved?
* reducing / removing logs that are super-long

**Comment by tokebe** [comment]
Above are new PRs addressing most of what's been discussed here for the first pass.

Like @colleenXu said, next pass will be more refinement of TRAPI logs (cutting unnecessary ones, making others more informative/using proper log level, adding useful logs, conforming language usage to a clear standard). I will see where I can do this but some logs are better changed by devs who are more familiar with specific sections.

Console logs are a lower priority but a running list of console log items which could stand to be shortened/removed will help for making the console logs a little easier to follow visually.

**Comment by colleenXu** [comment]
related to https://github.com/biothings/BioThings_Explorer_TRAPI/issues/392 since we were wondering how to make a log that says what non-TRAPI APIs are not available

**Comment by tokebe** [comment]
I'm marking this issue as closed. Obviously care must be taken as time goes on to find new areas to improve logging readability/information, however most of the issues with existing TRAPI logs have been fixed.

A sort of post-mortem list of continuing objectives determined in this issue (could stand to be added to a coding guide document):
- TRAPI logs priorities (in order):
  - Readable
  - Informative
  - Short
- Try to apply the above priorities to console `debug()` logs as well, where applicable.
- Strive to use TRAPI log levels as best as possible. A general guide:
  - If a random user doesn't need to know or probably wouldn't care unless they're digging into execution, it should be `DEBUG`. Consider if it should even exist at the `DEBUG` level. Does it give routinely useful information to a developer, or just kind of say that a specific fine-grain stage happened? If the latter, perhaps keep it only as a console `debug()` log.
  - If the user might want to know, or it summarizes a lot of other debug logs in a way that might still be useful to a user trying to gain cursory execution understanding, then it might fit at the `INFO` level.
  - If something has gone wrong, but it doesn't affect how the user should consider their results (could be missing results due to an API being down, but nothing will be 'wrong', etc.), it should probably be a `WARNING`.
  - If something has gone wrong, and it constitutes an internal code failure, or affects how the user should consider their results (could be incomplete/incorrect/etc.), it should probably be an `ERROR`.
