### ISSUE TITLE
Use semmeddb NGD handler as scoring/ranking engine in BTE

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#368]
With the completion of https://github.com/biothings/BioThings_Explorer_TRAPI/issues/326, we now need to incorporate the new NGD handler in the semmeddb API into a scoring/ranking scheme for BTE.  Creating this ticket to track ongoing work by @ericz1803.

**Comment by ericz1803** [comment]
The code for scoring using the SEMMED NGD handler is in the `score` branch of the `query_graph_handler` package.

So far, the performance seems to be alright but not great. This is a combination of the SEMMED NGD service getting an infinity or undefined score for some combos as well as the node normalizer not being able to find a UMLS ID for some IDs. Our strategy for scoring is getting the NGD from SEMMED then taking `1/ngd` to make it ascending since a higher NGD means two things are less related. In the case that it is a multiple hop query, we are multiplying the scores for each hop together. 

For Query 1, it is mostly the first case, where the SEMMED NGD service comes up with undefined or infinity results. 12/235 results came up with nonzero scores. 24 combos had no UMLS ID compared to 337 with results (12 nonzero combos). The reason this number is higher than the final results is some results have multiple UMLS ID combos.

For Query 2, it did better, with 431/1194 results coming up with nonzero scores. There were around 60 IDs node normalizer couldn't resolve. Around 50 were MEDDRA IDs, which node normalizer doesn't seem to support. There were a few MONDO IDs where node normalizer find a UMLS ID but it was easily found on the MONDO database (`MONDO:0005062`, `MONDO:0006918`) and a few where I couldn't find an exact match (`MONDO:0021668`, `MONDO:0005134`, `MONDO:0020249`).

<details>
<summary>MEDDRA ID List</summary>

```
MEDDRA:10070592
MEDDRA:10036500
MEDDRA:10053239
MEDDRA:10048870
MEDDRA:10054980
MEDDRA:10036898
MEDDRA:10044439
MEDDRA:10062117
MEDDRA:10038533
MEDDRA:10054133
MEDDRA:10050436
MEDDRA:10056350
MEDDRA:10053467
MEDDRA:10063370
MEDDRA:10072041
MEDDRA:10020388
MEDDRA:10024714
MEDDRA:10053469
MEDDRA:10061758
MEDDRA:10066536
MEDDRA:10064059
MEDDRA:10003835
MEDDRA:10059696
MEDDRA:10011603
MEDDRA:10061026
MEDDRA:10061852
MEDDRA:10063797
MEDDRA:10002781
MEDDRA:10051786
MEDDRA:10058845
MEDDRA:10063581
MEDDRA:10047991
MEDDRA:10061732
MEDDRA:10058909
MEDDRA:10015011
MEDDRA:10052018
MEDDRA:10029173
MEDDRA:10021430
MEDDRA:10036895
MEDDRA:10064979
MEDDRA:10052995
MEDDRA:10052617
MEDDRA:10068833
MEDDRA:10068369
MEDDRA:10042609
MEDDRA:10053757
MEDDRA:10049662
MEDDRA:10053314
```
</details>

<details>
<summary>Query 1</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:Disease"],
                    "ids": ["MONDO:0005737"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```
</details>

<details>
<summary>Query 2</summary>

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": [
                        "PUBCHEM.COMPOUND:5877", 
                        "PUBCHEM.COMPOUND:124653", 
                        "PUBCHEM.COMPOUND:6741"
                    ],
                    "categories": ["biolink:ChemicalEntity"],
                    "name": "Methylprednisone"
                },
                "n1": {
                    "categories": ["biolink:DiseaseOrPhenotypicFeature"]
                }
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:treats", "biolink:has_real_world_evidence_of_association_with"]
                }
            }
        }
    }
}
```
</details>

**Comment by colleenXu** [comment]
note that we would want a default score for results where an NGD score isn't found. Currently the default is 1, but maybe the default value needs to be dropped to 0?
