### ISSUE TITLE
handling unresponsive/slow non-TRAPI APIs

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#392]
brought up convo w/ @tokebe today. 

When the cron job is run, we believe the smartapi registry is pinged (for the latest data from there) and the /meta_knowledge_graph endpoints are pinged for all TRAPI apis. 

However, perhaps we only need to ping the APIs we actually use (the config file). 

Also, if one of the non-TRAPI APIs is down, we wouldn't know it until we saw all the failed/time-outs in sub-queries. It would help debugging, evaluating query runs, and make queries more efficient if we setup a way to ping those APIs during a cron job. Then if that API was unavailable, we'd put it in our logs + wouldn't send sub-queries to that api

**Comment by colleenXu** [comment]
may involve adding examples to endpoints (openapi) so then the smartapi registry pull "uptime" property should be an indicator of whether the api is up or not

**Comment by andrewsu** [comment]
> When the cron job is run, we believe the smartapi registry is pinged (for the latest data from there) and the /meta_knowledge_graph endpoints are pinged for all TRAPI apis.
> 
> However, perhaps we only need to ping the APIs we actually use (the config file).

In my mind, this is a low-priority item because the end result is the same.  We currently are just doing a few more calls than necessary, but this happens during the cron job so it doesn't affect query performance.

> Also, if one of the non-TRAPI APIs is down, we wouldn't know it until we saw all the failed/time-outs in sub-queries. It would help debugging, evaluating query runs, and make queries more efficient if we setup a way to ping those APIs during a cron job. Then if that API was unavailable, we'd put it in our logs + wouldn't send sub-queries to that api

I'm not sure I like this proposed behavior. If an API went down, I think we'd want to continue to query that API on subsequent queries rather than assume it was down until the next cron job update (on the assumption that the outage was sporadic and temporary).  Now if we had one TRAPI query that would spawn 50 subqueries to a given API, I think it would probably be fine to skip queries 2-50 if the first one failed.  (Or maybe skip 6-50 if the first five failed?)  I might change my opinion here if failed queries were greatly affecting query times...

**Comment by tokebe** [comment]
Summarizing [conversation in Slack](https://suwulab.slack.com/archives/CC218TEKC/p1645035128106589), a proposed behavior:

During the course of a query, if a sub-query fails due to timeout, that API is marked as 'down' on a 'cooldown' timer, say, for a period of 5 minutes. During this cooldown, any sub-queries to that API will be automatically skipped, **only within the execution of the BTE query in which the sub-query failed** (so, a per-query cooldown).

This should protect queries with many sub-queries to the same API from enormous delay due to each sub-query having to timeout, without costing other queries in the event the API came back up more quickly than expected.

Tagging @colleenXu @andrewsu @newgene for thoughts and discussion of this proposed behavior.

**Comment by andrewsu** [comment]
Yes, I generally agree with this proposed _per-query_ behavior.  Two parameters that could be used to tune -- the number of timeouts observed to trigger the cooldown (let's call this T), and then the length of the cooldown period (L).  @tokebe's proposal corresponds to T=1 and L=5 mins.  I'd be fine with that, or T=1 and L=999 mins (effectively removing that API from that query entirely), or T=5 and L=999 (maybe the API timed out on a particularly lengthy subquery, but otherwise it was fine?)...

**Comment by tokebe** [comment]
If the concern is execution time of a given query, each query times out after 50s, meaning that each failed query is almost another minute on execution time. That being the case I'd propose T=<2. 

I just stated an example L=5, in case it's a long query already and there's a chance it'll somehow query that API again, to give the API a chance to return to operation prior to the end of sub-queries, however it makes sense to simply disable that API for the duration of the query -- I have no opinion one way or the other on that. 

There's also an argument to be made to do something a bit more fine-grained, such as limiting to smaller sub-queries on first fail, and then disabling after the second, though implementation may be more complicated depending on how we'd want to do that.

**Comment by andrewsu** [comment]
Yeah, good points.  I vote T=1 and L=999 (or hard-coded to be indefinite). Agreed that we _could_ have more complex logic, but not necessary at this stage I think...

**Comment by colleenXu** [comment]
copying my feedback/testing from Slack:

This is an example query, since SequenceVariant operations use some APIs that get easily overwhelmed/timeout...
However, this query takes > 6 min to run.

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                },
                "e02": {
                    "subject": "n1",
                    "object": "n2"
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MONDO:0019391"],
                    "categories": ["biolink:Disease"]
                },
                "n1": {
                    "categories": ["biolink:SequenceVariant"]
                },
                "n2": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```

It looks like the new code does run.....but a careful look at internals/console-logs would be needed to check that (1) no more sub-queries to those apis are made during this query and (2) on the next query, the limits reset...
![Screen Shot 2022-02-22 at 5 35 17 PM](https://user-images.githubusercontent.com/43731687/156412268-3bd2deef-a31f-4ece-ad03-5f1fbc1819e1.png)

I see....it looks like the other sub-queries to an API in a "batch" (since sub-queries seem to be sent in sets of 3?) will still run, even if 1 of them hits a failure/timeout.
But subsequently, that API won't be used.

so....I think this PR looks good. But I don't feel like I did a thorough testing.
in order to test this, I think I need to change the timeout parameters for sub-queries and I'm not sure how to do this. Ideally, I think a test would be:
* do a multi-hop query where multiple hops involve the same API (that times out easily). Check that the API timeouts during the first executed hop, and then isn't used for the rest of the query (rest of that hop and later hops).
* Then run another query that also uses that API, and check that the limit resets.

**Comment by colleenXu** [comment]
@tokebe has said that running the query twice to check that the limit resets has been done. Jackson has also done more testing with this by changing the limits 
* https://github.com/biothings/call-apis.js/blob/73c26ea4200a28c8b165ef56f44e08f0e7da231b/src/builder/trapi_query_builder.js#L84
* https://github.com/biothings/call-apis.js/blob/73c26ea4200a28c8b165ef56f44e08f0e7da231b/src/builder/template_query_builder.js#L92
* https://github.com/biothings/call-apis.js/blob/73c26ea4200a28c8b165ef56f44e08f0e7da231b/src/builder/query_builder.js#L93

**Comment by tokebe** [comment]
I should note that groups of sub-queries are run nearly simultaneously, so in many cases a couple queries to the same API will happen and fail around the same time before the API is able to be marked as unavailable, however after the initial batch of around ~3 near-simultaneous failures, the rest will be skipped. 

The warnings in the TRAPI log reflect the actual number of queries skipped, so if 3 queries happen and fail, the count of skipped queries begins after that.

**Comment by colleenXu** [comment]
yep, the queries that fail are noted in a separate part of the logs (# of queries for the QEdge that were successfully executed vs failed). which is diff from skipping them. 

@tokebe can we close this issue now?
