### ISSUE TITLE
Inconsistent results when changing node category with identifier

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#444]
Described here: biothings/biothings.api/issues/223

**Comment by tokebe** [comment]
This would appear to be occurring because the SRI normalizer lookup doesn't return the category `Disease` for `HP:0000217` (as seen [here](https://arax.ncats.io/?term=HP:0000217)), causing category inference to determine `PhenotypicFeature` to be the most-specific category available. 

When instead `Disease` is specified as a category, category inference adds `PhenotypicFeature`, but as `Disease` is also kept, it causes additional sub-query operations to be found, specifically one with MyDisease which structures into the following query config:

```javascript
{
  url: "http://mydisease.info/v1/query",
  params: {
    fields: "disgenet.genes_related_to_disease.gene_id, disgenet.genes_related_to_disease.pubmed, disgenet.genes_related_to_disease.source, disgenet.genes_related_to_disease.DPI, disgenet.genes_related_to_disease.DSI, disgenet.genes_related_to_disease.EI, disgenet.genes_related_to_disease.score",
  },
  data: "q=C0043352&scopes=disgenet.xrefs.umls",
  method: "post",
  timeout: 50000,
  headers: {
    "User-Agent": "BTE/dev Node/v17.6.0 darwin",
  },
}
```

This and 3 other sub-queries return records which are kept in results assembly, with this specific query resulting in the addition of `IRF5`.

So, this would appear to be an issue with the SRI node normalizer not returning the complete set of categories? It could probably be resolved by modifying the category inference to take parent categories when not all child categories are present, however this would lead to other cases where inferred categories are made too general. Specific cases could be added, such explicitly applying said behavior to only mixins or a specific set of categories, though the latter would likely be trouble to maintain adequately.

Tagging @andrewsu @colleenXu for their thoughts.

**Comment by andrewsu** [comment]
I want to confirm my understanding here.  

**Case 1: If the query specifies `"categories": ["biolink:DiseaseOrPhenotypicFeature"]` for `n2` / `HP:0000217`**, then BTE will consult the biolink model and find its children `biolink:Disease` and `biolink:PhenotypicFeature`.  Then BTE will query the SmartAPI metakg to find APIs that link any of those _three_ categories with `biolink:Gene` (the category for `n01`).  And that query will result in both `IRF5` and `Amylases`.

**Case 2: If the query does not specify a category for `n2` / `HP:0000217`**, then BTE queries the node normalizer (https://nodenormalization-sri.renci.org/1.2/get_normalized_nodes?curie=HP:0000217) and determines that the appropriate category is `biolink:PhenotypicFeature`. So BTE will query the metaKG only linking `biolink:PhenotypicFeature` to `biolink:Gene`, and we miss `IRF5` because it presumably came from an API annotated to `biolink:Disease`

**Case 3: If the query specifies `"categories": ["biolink:PhenotypicFeature"]` for `n2` / `HP:0000217`**, we get the same behavior as not specifying a category for `n2` / `HP:0000217`, same as Case 2.

**Case 4: If the query specifies `"categories": ["biolink:Disease"]` for `n2` / `HP:0000217`**, somehow "category inference adds `PhenotypicFeature`" (quoting from @tokebe's last post), so BTE queries the metakg for APIs that link either of those _two_ class types (`biolink:PhenotypicFeature` or `biolink:Disease`) , and we get both `IRF5` and `Amylases`. 

Corrections/clarifications appreciated!

**Comment by colleenXu** [comment]
@tokebe Thanks for the detailed analysis. **My hunch was confirmed, and I think that the current behavior is fine.** I'll explain...

We rely on x-bte annotation of APIs that exist somewhat-outside of Translator. These data provided by 1 endpoint will often not cleanly fit into 1 biolink semantic type. 
*  For example, resources often use a particular ontology to label their entities (e.g. CHEBI for chemicals). But Translator/biolink-model/SRI-Node-Normalizer may map those CHEBI IDs to different semantic types (MolecularMixtures / SmallMolecules / etc). 
* The API's responses often don't include extra info from the ontology, that would help us filter responses for CHEBI IDs that only map to a particular biolink semantic type.
* It's not clear what SRI Node Normalizer is doing to map IDs to biolink semantic types. 

In this situation, we've been doing "fuzzy" or "somewhat-imprecise" mappings between the ID namespaces / ID sets used by an API endpoint + the biolink-model. This is more tractable and makes x-bte annotation easier to write. 
* In this issue's case, we've labeled all the UMLS IDs from the [DisGeNET data](https://www.disgenet.org/downloads) in MyDisease as Disease. And we've labeled HP IDs in various operations as PhenotypicFeatures (even though [some](https://arax.ncats.io/?term=HP:0000217) look like diseases and have been mapped by SRI Node Normalizer as biolink-model Disease). 
* In the case of CHEBI IDs, we label them as "SmallMolecule" in various operations. This is partially due to historical reasons (there used to be only a `ChemicalSubstance` semantic type, and that was mapped to SmallMolecule....so we map all chemical-things to SmallMolecule now)

Why don't we just strictly adhere to the SRI Node Normalizer's mapping of IDs? Well...
* we don't know how the SRI Node Normalizer does this mapping (for example, I've opened this ticket on how this [UMLS mapping doesn't match the biolink-model](https://github.com/TranslatorSRI/Babel/issues/530)). And even if we knew that...
* imagine asking every API (some of which are completely external to our team/Translator) for ALL IDs in the underlying data for each endpoint. Then we can map ALL of them to the biolink-model with SRI Node Normalizer.....which may hit issues if the vocab/IDs aren't covered by the service. And then we write x-bte operations for each biolink-semantic type returned by each endpoint. But we probably can't query the endpoint with such specificity (for example, only return the IDs corresponding to a specific biolink-semantic type)...

Can we do better?
* In this specific situation, we could....maybe. 
    * DisGeNET's [data](https://www.disgenet.org/static/disgenet_ap1/files/downloads/readme.txt) includes a diseaseType column which we haven't been parsing. This [column](https://www.disgenet.org/dbinfo#section43) uses DisGeNET's mapping of UMLS IDs into "disease", "phenotype", and "group". I only took a quick look, but I think they somewhat correspond to biolink-model's Disease (DisGeNET "disease" and "group") and PhenotypicFeature (DisGeNET "phenotype"). I think they might not exactly match though...
    * If we include the diseaseType in MyDisease's DisGeNET data, we may be able to write more specific operations since we'll be able to query for subsets of the DisGeNET data. 
* This is really on an endpoint-by-endpoint / API-by-API basis. It depends a LOT on whether resources allow specific querying based on the intricacies of the vocabs they use...

**Comment by colleenXu** [comment]
Err to address Andrew...

@andrewsu All the cases, but particularly 1 and 4, relate to #418 . We decided to keep the categories provided by the user (and expand with biolink-model's hierarchy), while also adding the most-specific category provided by SRI Node Normalizer (first category in the array) **when it differs**. 

Otherwise, I think your post is correct.

I'll note that the decisions made in #418 are related to: 
* the "fuzziness" of the x-bte annotation (explained in detail in the above post). We may want to query with ChemicalEntity/SmallMolecule because we've annotated the endpoint with those terms, even though some IDs returned by that endpoint might map to a different biolink-semantic-type for SRI Node Normalizer. 
* the user might not really be "wrong" in their choice of semantic type. For example, for data sources like SEMMEDDB, the UMLS-semantic-type for an ID may differ between associations. In this situation, multiple options for semantic type are given by the UMLS Browser (see [Tyrosine](https://uts.nlm.nih.gov/uts/umls/concept/C0041485)). The user might understandably pick 1 semantic type, when another is also possible for that ID.

**Comment by colleenXu** [comment]
And TDLR for the big comment above @tokebe @andrewsu:
* I think the current behavior is fine. Perhaps MyDisease's parsing of DisGeNET could be improved, and then we could edit the x-bte annotations
* I think any fixes for this would have unintended consequences. For example, maybe one decides to write a Disease->Gene and a Phenotype->Gene operation for the MyDisease-DisGeNET query. But this is still the same underlying sub-query for either operation.....so if someone uses a more general category somewhere in the TRAPI query, you'll end up running the same sub-query twice and maybe treating the results as two separate sets of data when they aren't...
* This is why we currently keep 1 operation for each combo of a specific endpoint/ query structure / output-ID-field / output-ID-namespace. So we don't end up running redundant sub-queries and treating the responses as separate sets when they aren't....

**Comment by cbizon** [comment]
Interesting issue - I can speak a little bit about what nodenorm is doing, though I don't know that it will shed any light on this.  It's a difficult problem because you have many vocabularies and we are finding equivalent identifiers across them, and then those different vocabularies assign classes to this new thing that may or may not agree with one another.    Disease/Phenotype is probably the worst offender, because it's really not clear what the difference even is.

There are a number of ways to approach that problem, but the one that we chose is to establish some (fairly ad-hoc) practical rules to assigning a class to a clique.   They're situationally dependent to handle cases like the ones @colleenXu noted above where HP has things in it that sure look like diseases to everybody else.   We're thinking of cleaning up disease/phenotype by treating it as a conflation like we do for genes/proteins so that people can keep things more carefully pulled apart and then merge as needed.  Would that help in this case?

As far as helping this particular issue, I am certainly no bte annotation expert, so take this with a grain of salt, but I think of those annotations as defining what kinds of things (in biolink/translator speak) you are getting from this api.  In this case, it seems like you're getting both diseases and phenotypes, so can the annotation just include both?

**Comment by andrewsu** [comment]
@cbizon we discussed this issue at our internal meeting earlier, and we ended up with these two points:

* Conflation of `Disease` with `PhenotypicFeature` seems like a reasonable way to ensure consistency in the various versions of this query.  It is perhaps timely in that it ties into some upcoming discussions in the Data Modeling group around other conflations (genes and genomes, drugs and smallMolecules, etc.).  The main question here is whether that gets individually implemented by each tool, or whether that gets implemented through node normalizer.  (Since we already [implemented](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/319) Gene / Protein conflation in BTE, that would be simple enough for us to follow that same pattern within BTE again...)

* Regarding editing smartAPI annotations to ensure consistency, while it's a possible solution it is one that we are not enthusiastic about.  It would be a lot of work and there are lots of issues with generalizability and readability that make the net benefit a bit less clear...

**Comment by cbizon** [comment]
Ok, I think disease/phenotype conflation is something that should be handled at the node normalization level.  In general, I think we need to discuss on the Architecture call whether we have a single source of truth for the classes of things.  So if I have an identifier, can we all agree that it's a Disease?

For editing smartAPI annotations, I guess I'm not sure what the issue is.   It seems to me that if the API is returning identifiers and you can't change what they are, and if the identifiers are given a biolink type within translator, then the annotations should reflect the translator types of the identifiers that one might get back from a call to the API.  But there are numerous "ifs" in that statement...

**Comment by tokebe** [comment]
Should be resolved by https://github.com/biothings/bte_trapi_query_graph_handler/pull/106?

**Comment by colleenXu** [comment]
I think so? I didn't test this [one](https://github.com/biothings/bte_trapi_query_graph_handler/pull/106#issuecomment-1183657460) though...

**Comment by tokebe** [comment]
Marking as resolved (forgot to add that I had tested the above-mentioned PR prior to merging).
