### ISSUE TITLE
Utilize UMLS concept tree in NGD handler on SemMedDB API 

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#459]
In https://github.com/biothings/BioThings_Explorer_TRAPI/issues/326, @erikyao created a custom handler to compute a Normalized Google Distance (NGD) based on the SemMedDB API.  The NGD endpoint takes two UMLS IDs as input, and outputs a simple JSON structure that includes the computed NGD:

https://biothings.ncats.io/semmeddb/query/ngd?umls=C0684074,C0003063

```
{
    "umls": [
        "C0684074",
        "C0003063"
    ],
    "ngd": 0.8219458152012636
}
```

There are many cases where the returned NGD score is infinite.  According to the [documentation](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/326#issuecomment-965856386), this occurs when "when two terms that separately occur in the corpus, but never occur together".   For example, the NGD between "doxorubicin" ([C0013089](https://uts.nlm.nih.gov/uts/umls/concept/C0013089)) and "Sarcoma of soft tissue" ([C4551687](https://uts.nlm.nih.gov/uts/umls/concept/C4551687)) is reported as Infinity (https://biothings.ncats.io/semmeddb/query/ngd?umls=C0013089,C4551687).

However, even though "doxorubicin" never co-occurs with "Sarcoma of soft tissue" in a semmeddb record, "doxorubicin" _does_ co-occur with "leiomyosarcoma" ([C0023269](https://uts.nlm.nih.gov/uts/umls/concept/C0023269)), and "leiomyosarcoma" is a child (or "narrower concept" in UMLS) of "Sarcoma of soft tissue".  Our NGD handler correctly reports a non-infinite NGD for this pair of concepts: https://biothings.ncats.io/semmeddb/query/ngd?umls=C0013089,C0023269.

**I propose an enhancement on the NGD handler so that the UMLS concept tree is incorporated into the calculation of NGD**.  That would mean that in calculating the NGD between "doxorubicin" and "Sarcoma of soft tissue", the NGD handler would look at co-occurrence of "doxorubicin" *and any of its children* with "Sarcoma of soft tissue" *and any of its children*.

Assigning to @erikyao to assess feasibility...

**Comment by erikyao** [comment]
## How to calculate

Let's define:

- $S(x, \dots)$, the set of documents containing all the concepts/terms $x, \dots$. 
- $f(x, \dots)$, the number of documents containing all the concepts/terms $x, \dots$. 
    - which means $f(x, \dots) = \vert S(x, \dots) \vert$

Given $f(x, y) = 0$, if concept/term $x$ has two children $x_1$ and $x_2$, then we calculate $f(x, y) = \vert S(x_1, y) \cup S(x_2, y) \vert$ 

- Consider one document that contains both $x_1$ and $x_2$. It should contribute only 1 count to $f(x, y)$, and that's why we take the union of $S(x_1, y) \cup S(x_2, y)$.

Questions:

1. shall we use the original $f(x)$, or re-calculate $f(x) = \vert S(x_1) \cup S(x_2) \vert$?
    - Answer: re-calculate
1. shall we also consider $y$'s children $y_1, y_2, \dots$? 
    - Answer: could have another query parameter, say `extensive`
        - `/query/ngd?umls=x,y&extensive=x` $\Rightarrow$ consider $x$'s children only
        - `/query/ngd?umls=x,y&extensive=y` $\Rightarrow$ consider $y$'s children only
        - `/query/ngd?umls=x,y&extensive=x,y` $\Rightarrow$ consider $x$'s and $y$'s children both
            - `extensive=x,y` could be made default

## More on the `extensive` mode

From Andrew, instead of only when `f(x,y)=0`:

> I think we would _**always**_ want to do it (when `extensive=x,y` that is).  So in some way, I think $f(x) = \vert S(x) \cup S(x_1) \cup S(x_2) \vert$

## How to implement

Boils down to how to obtain the "concept tree". Websites mentioned in 06/22 meeting for reference:

- [Semantic Network](https://lhncbc.nlm.nih.gov/semanticnetwork/#label:download)
  - [Fact Sheet (archive)](http://wayback.archive-it.org/org-350/20180312141727/https://www.nlm.nih.gov/pubs/factsheets/umlssemn.html)
  - [UMLS Semantic Network Browser](https://uts.nlm.nih.gov/uts/umls/semantic-network/root)
- [Metathesaurus](https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/index.html)
- [Retrieving UMLS Concept Relations](https://documentation.uts.nlm.nih.gov/rest/relations/)
  - [E.g. Alzheimer's Disease](https://uts.nlm.nih.gov/uts/umls/concept/C0002395)

Caches also need to be extended for the `extensive` NGD values.

**Comment by erikyao** [comment]
**DDL:** would be nice if we finish it mid August.

**Comment by colleenXu** [comment]
I can get from leiomyosarcoma to sarcoma with this [endpoint](https://documentation.uts.nlm.nih.gov/rest/relations/): https://uts-ws.nlm.nih.gov/rest/content/current/CUI/C0023269/relations?includeRelationLabels=RN&pageSize=1000&sabs=MTH (add your apiKey as a parameter). 

I can get in the opposite direction from sarcoma to leiomyosarcoma too: https://uts-ws.nlm.nih.gov/rest/content/current/CUI/C1261473/relations?includeRelationLabels=RB&pageSize=1000&sabs=MTH (add your apiKey as a parameter). 

Note the use of the parameters. It's confusing that the relation labels seem to be the opposite direction of what I would expect...

**Comment by erikyao** [comment]
Also from Colleen:

> also noting a useful link for abbreviations in UMLS https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/release/abbreviations.html#mrdoc_REL

**Comment by andrewsu** [comment]
assigning to @tokebe to create the BTE PR to use the new `expand` parameter

**Comment by colleenXu** [comment]
linking to https://github.com/biothings/bte_trapi_query_graph_handler/pull/121

**Comment by andrewsu** [comment]
confirmed with @tokebe that this issue is complete.
