### ISSUE TITLE
add a small value to all edge scores

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#553]
Right now, BTE reports a score for each result that is the sum of the semmeddb NGD scores for each edge in the result.  In cases where the NGD score(s) are all zero (which occurs when semmed does not report any publications that co-mention the two concepts), then the overall result score is zero.  

I would like to change this behavior to add a small score for every edge in the result.  The rationale is two-fold:
* the ARAX UI currently returns `n/a` when the score is zero, leading to some confusion
* from a user perspective, a zero score doesn't make sense, since the fact that BTE retrieves the edge is alone worth something

So to start, I propose adding a value of `0.1` to the NGD score for every edge.

**Comment by tokebe** [comment]
implemented in https://github.com/biothings/bte_trapi_query_graph_handler/commit/62b4ea17af9ab12369ac8e698a7a630d2da961ea

**Comment by colleenXu** [comment]
From today's lab meeting: 

Jackson implemented adding 0.1 to each result (aka 0.1 became the baseline) [above](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/553#issuecomment-1412272795). 

We discussed the wording of the original post and clarified that AS actually asked for adding 0.1 * (number of edges in result) to the current score.

---

Other notes:
* The current score is the sum of pairwise NGD scores from semmeddb, where the pairs come from the UMLS IDs of the result nodes. (number of pairs) =/= number of edges in the result because each result node can have > 1 equivalent UMLS ID. See [issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/368) and [PR
](https://github.com/biothings/bte_trapi_query_graph_handler/pull/98)
* Related to this issue of [custom weighing](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/550). We could increase / decrease "weights" added to the result score based on what the edge came from

**Comment by tokebe** [comment]
Behavior corrected by https://github.com/biothings/bte_trapi_query_graph_handler/commit/e81dee9ba5710dc8123e37d28b21bba701770678

Leaving issue open until deployment to prod, whoops :P

**Comment by tokebe** [comment]
Deployed to prod 🚀
