### ISSUE TITLE
Annotate the official CTD API in SmartAPI

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#558]
The official CTD API is documented at http://ctdbase.org/help/linking.jsp, and it appears to my eye to be a "standard" association-based style.  There is value in annotating their API instead of standing up one of our own, especially given their [restrictive licensing terms](http://ctdbase.org/about/legal.jsp). So, we should put in some reasonable effort to see if we can incorporate it properly.  (Note also that this is a completely open API, in contrast to Drugbank's API which requires an API key.)

NOTES:
* There was a previous effort to annotate the CTD API at https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml, but it uses an older smartAPI format.  More context at: https://github.com/biothings/BioThings_Explorer_TRAPI/issues/372#issuecomment-1075990125
* CTD provides both "curated" relationships and "inferred" relationships.  The API can return either/both based on API call parameters.  We should emphasize the "curated" subset initially, and the "inferred" should be clearly distinct (a separate SmartAPI entry, or a different `infores` in the provenance, or something similar)
* The API can return relationships between chemicals, genes, diseases, and pathways.  We should annotate meta-edges for all pairs of node types.

Example API call looking for curated relationships linking the chemicals acivicin (C006303) and Aclarubicin (D015250) to diseases is here: http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=C006303|D015250&report=diseases_curated&format=json 

Output:
```
[
{
  "CasRN": "52583-41-2",
  "ChemicalID": "C006303",
  "ChemicalName": "acivicin",
  "DirectEvidence": "therapeutic",
  "DiseaseCategories": "Digestive system disease",
  "DiseaseID": "MESH:D002779",
  "DiseaseName": "Cholestasis",
  "Input": "c006303",
  "PubMedIDs": "7624871"
},
{
  "CasRN": "52583-41-2",
  "ChemicalID": "C006303",
  "ChemicalName": "acivicin",
  "DirectEvidence": "therapeutic",
  "DiseaseCategories": "Metabolic disease|Urogenital disease (female)|Urogenital disease (male)",
  "DiseaseID": "MESH:D006029",
  "DiseaseName": "Glycosuria",
  "Input": "c006303",
  "PubMedIDs": "1673268|2867768|7909430"
},
{
  "CasRN": "52583-41-2",
  "ChemicalID": "C006303",
  "ChemicalName": "acivicin",
  "DirectEvidence": "marker/mechanism|therapeutic",
  "DiseaseCategories": "Urogenital disease (female)|Urogenital disease (male)",
  "DiseaseID": "MESH:D007674",
  "DiseaseName": "Kidney Diseases",
  "Input": "c006303",
  "PubMedIDs": "1673268|2867768|3200250|7909430|9637657"
},
{
  "CasRN": "52583-41-2",
  "ChemicalID": "C006303",
  "ChemicalName": "acivicin",
  "DirectEvidence": "therapeutic",
  "DiseaseCategories": "Cancer",
  "DiseaseID": "MESH:D009369",
  "DiseaseName": "Neoplasms",
  "Input": "c006303",
  "PubMedIDs": "22996645"
},
{
  "CasRN": "57576-44-0",
  "ChemicalID": "D015250",
  "ChemicalName": "Aclarubicin",
  "DirectEvidence": "therapeutic",
  "DiseaseCategories": "Cancer",
  "DiseaseID": "MESH:D015470",
  "DiseaseName": "Leukemia, Myeloid, Acute",
  "Input": "d015250",
  "PubMedIDs": "1942537|32929351"
},
{
  "CasRN": "57576-44-0",
  "ChemicalID": "D015250",
  "ChemicalName": "Aclarubicin",
  "DirectEvidence": "therapeutic",
  "DiseaseCategories": "Cancer",
  "DiseaseID": "MESH:D015473",
  "DiseaseName": "Leukemia, Promyelocytic, Acute",
  "Input": "d015250",
  "PubMedIDs": "32929351"
},
{
  "CasRN": "57576-44-0",
  "ChemicalID": "D015250",
  "ChemicalName": "Aclarubicin",
  "DirectEvidence": "marker/mechanism",
  "DiseaseCategories": "Pathology (process)",
  "DiseaseID": "MESH:D009336",
  "DiseaseName": "Necrosis",
  "Input": "d015250",
  "PubMedIDs": "20399885"
},
{
  "CasRN": "57576-44-0",
  "ChemicalID": "D015250",
  "ChemicalName": "Aclarubicin",
  "DirectEvidence": "marker/mechanism",
  "DiseaseCategories": "Cardiovascular disease|Pathology (process)",
  "DiseaseID": "MESH:D016171",
  "DiseaseName": "Torsades de Pointes",
  "Input": "d015250",
  "PubMedIDs": "1942537"
}
]

```

**Comment by rjawesome** [comment]
@colleenXu See https://gist.github.com/rjawesome/7d7a35d75760e4656354c1d2248bae5e. This annotation should work.

**Comment by colleenXu** [comment]
### Update

I've updated SmartAPI [yaml](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/CTD/smartapi.yaml), but I haven't re-registered it yet. 

x-bte operations were written for some curated information only (what was excluded is discussed in the "BTE output-processing issue" and "Info we may want to annotate later" sections). 

### Some notes for future follow-up (probably not barriers to deployment)

<details>
<summary>Uptime-checking issue</summary>

I have added example parameters for SmartAPI registry uptime-checking, but commented them out. 

In the SmartAPI editor, queries to the endpoint wouldn't run successfully, but they'd run fine through Postman. When I pasted the GET urls into a browser, I'd be prompted to download the response as a JSON file. 

Possible solution: some more OpenAPI annotation for the endpoint (header info?)

</details>

<details>
<summary>Batch-query support issue</summary>

The operations are written as not-batch-query. However, CTD API can actually accept multiple input IDs (`|`-delimited string). The API response is an array of associations (objects) that doesn't separate matches for 1 input ID vs another - so BTE's default response-transform isn't handling this properly

Possible solution: a **custom api-response-transform**. The response does have an "Input" property for each association where the value is the input ID (all lowercase, has ID namespace prefix in some cases), which may be helpful

</details>

<details>
<summary>BTE output-ID-processing issue: commented out some operations</summary>

Some operations are commented-out because BTE isn't properly handling the output IDs when multiple ID prefixes are possible. 

* chem -> disease
* gene -> disease
* gene -> pathway

This happens for diseases (can be MESH or OMIM) and pathways (can be REACT or KEGG). For example, if a response has 1 association with a MESH DiseaseID and another association with an OMIM DiseaseID, BTE's default is to treat both of these IDs as whatever the operation/MetaEdge assigned (which is a single prefix). 

Possible solution: **custom api-response-transform**. 

This is related to past discussions on supporting multiple ID prefixes/namespaces as input / output (issue not written up yet). So it's a more widespread issue / could involve more refactoring of code + x-bte annotation...

</details>

<details>
<summary>Info we may want to annotate later</summary>

curated: 
* chemical <–> gene interactions (report: cgixns). Involves quite a bit of work, since actionTypes must be set and there's a lot of options (also this will differ between biolink2 and biolink3...)
* gene -> gene: response objects aren't consistent. Sometimes the input gene is the "src" and sometimes the "tgt" and vice versa for the output gene. This could possibly be addressed by the **custom api-response-transform**...Info may also be redundant: it may be from BioGRID, which is also a source for Biolink/Monarch's gene-gene data. 
* gene <-> go: redundant? currently we get this info from MyGene. We could also try getting this info from Biolink/Monarch

Non-curated info: also waiting for a way to annotate as curated vs not...
* chemical <-> disease
* chemical -> pathway (one way): no curated version, only "inferred" and "enriched". Uses gene intermediates
* chemical -> go (one way): no curated version, only "enriched". Uses gene intermediates    
* disease <-> gene 
* disease <-> pathway: no curated version. Uses gene intermediates
* go terms -> diseases (one way): no curated version. Uses gene intermediates

</details>

**Comment by colleenXu** [comment]
**Update on previous post, after 2023-03-13 discussion with Andrew Su**

* We discussed the notes above, and I'm writing up them up as new issues that I'll link to this one. 
* did a [minor update to the endpoint spec](https://github.com/NCATS-Tangerine/translator-api-registry/commit/d60f0e1aa939bb3c538cf0ae08328b7ce7d69df3)
* [registered the SmartAPI yaml](https://smart-api.info/registry?q=0212611d1c670f9107baf00b77f0889a) (it's now accessible to the smartapi-specific endpoints like v1/smartapi/{smartapi_id}/query)
* made a PR allowing the rest of BTE (team-specific / ARA) to use CTD. https://github.com/biothings/BioThings_Explorer_TRAPI/pull/582

**Comment by colleenXu** [comment]
since PR allowing the rest of BTE (team-specific / ARA) to use CTD was merged, I'm moving this issue. Once it's fully deployed, we can consider closing this issue.

**Comment by tokebe** [comment]
Deployed to prod 🚀 

Tagging @colleenXu for review if there's anything else or if the issue should remain closed
