### ISSUE TITLE
optional: readme/webpage on scoring method and creative-mode implementation?

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#616]
would be useful documentation. 

inspired by existence of result.analyses.scoring_method ([link](https://github.com/uhbrar/ReasonerAPI/blob/61fe8c40c88ba4dca182eb9ba0cb1ffa861aa75e/TranslatorReasonerAPI.yaml#L548))

Maybe this page would also include an explanation of our creative-mode method?

```
        scoring_method:
          type: string
          description: >-
            An identifier and link to an explanation for the method used
            to generate the score
          nullable: true
```

However, I'm not sure we'd want to actually add this property to every result.analyses for every result...

**Comment by tokebe** [comment]
Putting this one on-hold. 

Tagging @andrewsu to check if this should be closed as not planned, or is worth doing at some point at a lower priority.

**Comment by andrewsu** [comment]
The wiki page for BTE is at https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-Explorer-(BTE).  I just updated it with some additional details of our creative mode implementation and scoring (projecting ahead a tiny bit to when our scoring overhaul is done).  Anyone is welcome to continue to edit that page (but it is "good enough" for now).  Since that page is listed in the [infores catalog entry for BTE](https://github.com/biolink/biolink-model/blob/master/infores_catalog.yaml#L533), a link to that page will be displayed in the Translator UI.  I do not think we should add this link to `result.analyses.scoring_method`.
