### ISSUE TITLE
update semmeddb SmartAPI based on domain/range constraint curation

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#669]
In https://github.com/NCATSTranslator/Feedback/issues/369, Translator is codifying domain/range constraints that should be used to filter semmeddb.  This ticket will track the task of reflecting that work in our [SmartAPI annotation for semmeddb](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/semmeddb/smartapi.yaml).

**Comment by colleenXu** [comment]
Basic implementation of this is done https://github.com/NCATS-Tangerine/translator-api-registry/commit/67db272f75b1a39b7c2c859b486a1b6f94f9ab71 and deployed (registration refreshed)

**Comment by colleenXu** [comment]
The domain / range constraints are still implemented in the later commits refactoring x-bte generation. 
* https://github.com/NCATS-Tangerine/translator-api-registry/commit/0b083a9f814e36f8e5b1fa4635ec64a5df969202
* https://github.com/NCATS-Tangerine/translator-api-registry/commit/b08b9b3ff61ddab746bd6175e006e89c7dfbed7d

We still do some custom processing, basically 5 things (EDIT to make less text collapsed).

(These notes are included throughout the notebook, with **PAUSE** for the dev to re-evaluate the logic + code and make adjustments if needed.) 

1. There's a lot done in the parsing / deploying of the BioThings SEMMEDDB API. Including removing triples where the novelty of subject or object is 0, mapping retired IDs to new valid ones, etc. Would need to look into older issues or ask Yao for details. 
2. we don't make x-bte annotations from any meta-triples with a predication count <= 100 (roughly corresponds to ~ 10 records with pmid_count > 3)
3. We exclude 7 SEMMED predicates (+all the negation ones). 

<details><summary>click here to expand</summary>

* Translator currently isn't great with negation, so removing those
* I didn't find the following relationships useful: 
    * ISA (subclass relationship)
    * lower_than / higher_than (these two entities were compared and 1 was better (higher) or worse (lower) than the other)
    * compared_with...
* biolink-model issues
    * no biolink-model mapping: METHOD_OF, MEASUREMENT_OF
    * no biolink-model inverse (MISSING) and other issues:
        * ISA: already removed from data during Basic Filtering section 2.3 (predicates)
        * MEASURES: mapping isn't to a predicate (quantifier_qualifier)

</details> 

4. we didn't make operations for 17 SEMMED semantic-types that we didn't successfully find biolink-model mappings for, when using the toolkit. EDITED TO INCLUDE AN ANALYSIS

<details><summary>Click here for analysis</summary>
<p>

Wasn't reviewed in Translator's curation of semantic types:
* alga (Algae)
* invt (Invertebrate): is in biolink-model (Invertebrate), so that's odd
* rich (Rickettsia or Chlamydia)

Curation allowed these, but didn't successfully find mapping using toolkit. [Google sheet contains classifications?](https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=1662224030)
* arch (Archaeon): labeled as Organism/Taxon
* bdsy (Body System): Anatomy
* euka (Eukaryote): Organism/Taxon
* genf (Genetic Function): Biological Activity. Actually in biolink-model (broad-map to MolecularActivity and narrow-map to PhysiologicalProcess), so that's odd
* orgm (Organism): Organism/Taxon. is in biolink-model (Organism Taxon), so that's odd
* sbst (Substance): Substance

Stuff that was excluded + lacked biolink-model mappings: not really worried about these...
* bird (Bird): labeled as Organism/Taxon in [Google sheet](https://docs.google.com/spreadsheets/d/1c1gx0Jgm9rJUOXcQhBtZgvx50Cvz1-jh0DdGtg1zcd8/edit#gid=1662224030)
* bmod: Other
* chvf (Chemical Viewed Functionally): Chemical
* chvs (Chemical Viewed Structurally): Chemical
* ffas (Fully Formed Anatomical Structure): Anatomy
* fish (Fish): Organism/Taxon
* ocdi (Occupation or Discipline): Other
* rpt (Reptile): Organism/Taxon

![Screen Shot 2023-08-08 at 12 56 50 AM](https://github.com/biothings/biothings_explorer/assets/43731687/73a6520b-809a-4363-a912-6803494c82dd)

</p>
</details> 

5. 4 SEMMED semantic-types we use different mappings (not biolink-model):
* antb (Antibiotic) from biolink:Drug -> biolink:SmallMolecule
* phsu (Pharmacologic Substance) from biolink:Drug -> biolink:SmallMolecule
* gngm (Gene or Genome) from biolink:GenomicEntity -> biolink:Gene
* nnon (Nucleic Acid, Nucleoside, or Nucleotide) from biolink:NucleicAcidEntity -> biolink:SmallMolecule

**Comment by colleenXu** [comment]
Going to close this issue as complete. 

I think we should open new issues if things arise like:
* another wave of Translator-curation of SEMMEDDB, so the exclusions / constraints are updated
* changed expectations (not a simple include / exclude?)
* missing MetaEdges / trouble retrieving desired records or info
* bugs / problems...

**Comment by colleenXu** [comment]
Adding more info:

Implementing these Translator-curated exclusions led to a net increase in operations. This is mostly because I removed many custom exclusions of semmed semantic types...and used the Translator-curated work instead. 

Proof: net change of + 1438 operations
* Before, there were [2498 operations](https://github.com/NCATS-Tangerine/translator-api-registry/blob/d7307e8b50da8be0bd466bb9c81368e4b0fc4d38/semmeddb/generated_list.yaml)
* After I reinstated the custom predication filter of 100 (same as before), there were [3936 operations](https://github.com/NCATS-Tangerine/translator-api-registry/blob/0b083a9f814e36f8e5b1fa4635ec64a5df969202/semmeddb/generated_list.yaml). 

<details><summary>Analysis of added operations</summary>

There were semantic types allowed after Translator-curation (previously, I had excluded it, in my custom setup). This added 1590 operations. Note that the counts in the table below are approximate (could be less). 

| Abbrev | Full Name | # operations added |
|--------|--------|--------|
| elii | Element, Ion, or Isotope | 87 |
| nusq | Nucleotide Sequence | 156 |
| biof | Biologic Function | 96 |
| anst | Anatomical Structure | 26 |
| bdsu | Body Substance | 67 | 
| fndg | Finding | 96 |
| irda | Indicator, Reagent, or Diagnostic Aid | 89 |
| lbtr | Laboratory or Test Result | 17 |
| emod | Experimental Model of Disease | 72 | 
| orga | Organism Attribute | 14 |
| aggp | Age Group | 66 |
| virs | Virus | 127 |
| bact | Bacterium | 129 | 
| blor | Body Location or Region | 27 |
| bodm | Biomedical or Dental Material | 54 |
| bsoj | Body Space or Junction | 25 |
| dora | Daily or Recreational Activity | 18 | 
| eehu | Environmental Effect of Humans | 6 |
| emst | Embryonic Structure | 34 |
| fngs | Fungus | 91 |
| inbe | Individual Behavior | 14 | 
| medd | Medical Device | 61 |
| plnt | Plant | 30 | 
| rcpt | Receptor | 126 |
| tisu | Tissue | 62 |

Looking at things predicate-wise instead:
* allowing same_as added 56 operations
* allowing USES added 296 operations

</details>

But there were definitely operations removed as well (hundreds?), likely from the domain-predicate and range-predicate exclusions. Some examples I found:
* bpoc-LOCATION_OF-hops
* celc-AFFECTS-celf and its rev
* dsyn-PRODUCES-bac and its rev

**Comment by colleenXu** [comment]
And edited the [post above on the custom processing we do](https://github.com/biothings/biothings_explorer/issues/669#issuecomment-1669117440), including a new analysis of the 17 semantic types we exclude. 

Later, we could REVISIT what we do to see if we can be more aligned with other efforts / what Translator wants...
