### ISSUE TITLE
Error handling for async queries not working properly

### ISSUE THREAD

**Issue by rjawesome** [biothings/biothings_explorer#671]
(I noticed this while setting up error handling with sentry)
When an async query throws an error (even one that the user should know about, such as InvalidQueryGraph exception), the user is not given the error and is instead given a cryptic message on the response url.

Make an async query that should throw an error.

In this example, I use a cyclical query graph which throws an InvalidQueryGraph exception
(post this to https://api.bte.ncats.io/v1/asyncquery or localhost:port/v1/asyncquery)
```json
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "categories": ["biolink:Gene"],
          "ids": ["NCBIGene:3778"]
        },
        "n1": {
          "categories": ["biolink:Gene"]
        },
        "n2": {
          "categories": ["biolink:SmallMolecule"]
        }
      },
      "edges": {
        "e01": {
          "subject": "n0",
          "object": "n1"
        },
        "e02": {
          "subject": "n1",
          "object": "n2"
        },
        "e03": {
            "subject": "n2",
            "object": "n0"
        }
      }
    }
  }
}
```

Then, after a minute or so, check the status of the query via the URl given from the asyncquery request.
Here it will say the job is "Completed" and give you a response url.

When you go to the response url, it says
```
{"status":500,"description":"RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: JobQueuingError"}
```
This gives no indication to the user of the actual error (that their query graph was cyclical) and it doesn't make sense there there should be an invalid http status code here.

Here's an example of what it shows on production (BTE w/ TRAPI 1.3) for a similar query
![image](https://github.com/biothings/biothings_explorer/assets/16053597/2ff0dcb6-067a-4467-b109-3d42c62145ff)

**Comment by tokebe** [comment]
Just as a note, the expected TRAPI 1.4 response format can be seen [here](https://github.com/NCATSTranslator/ReasonerAPI/blob/b6a8de72529687fc21e247e599ca4180c22b8089/TranslatorReasonerAPI.yaml#L213-L250) and [here](https://github.com/NCATSTranslator/ReasonerAPI/blob/b6a8de72529687fc21e247e599ca4180c22b8089/TranslatorReasonerAPI.yaml#L373-L415).

So, we'd definitely want it to state "Failed" rather than "Completed" on the status endpoint, along with the error message propagated up to the description. The actual TRAPI response should still contain the query graph if possible, so basically what the 1.3 response looks like. The exact TRAPI 1.4 response spec can be seen [here.](https://github.com/NCATSTranslator/ReasonerAPI/blob/b6a8de72529687fc21e247e599ca4180c22b8089/TranslatorReasonerAPI.yaml#L416-L467)

**Comment by tokebe** [comment]
This would seem to be a higher priority issue than expected, as the majority of errors BTE will be reporting in production are through the async handling code. @rjawesome, you said you had a good idea of what was causing this?

**Comment by rjawesome** [comment]
I think I have a working fix. I will look at the other issue as well.
