### ISSUE TITLE
annotate gene-phenotype associations in HPO API

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer#710]
With the completion of https://github.com/biothings/pending.api/issues/24, ready to make updates to the [HPO SmartAPI annotation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/hpo/smartapi.yaml) to retrieve these associations.

Example record relating `HP:0032330` to `NCBIGene:1584` and `NCBIGene:1586` https://biothings.ncats.io/hpo/phenotype/HP:0032330

```
{
  "_id": "HP:0032330",
  "_version": 1,
  "ancestors": [
    "HP:0000818",
    "HP:0012029",
    "HP:0000118",
    "HP:0000001"
  ],
  "annotations": [
    {
      "disease_id": "ORPHA:90793",
      "gene": {
        "id": "1586",
        "symbol": "CYP17A1"
      }
    },
    {
      "disease_id": "ORPHA:90795",
      "gene": {
        "id": "1584",
        "symbol": "CYP11B1"
      }
    }
  ],
  "children": [],
  "comment": "Increased urinary 11-deoxycorticosterone is associated with congenital adrenal hyperplasia due to 11 beta-hydroxylase (CYP11B1) deficiency.",
  "def": "An abnormally elevated concentration or amount of 11-deoxycorticosterone in the urine. [https://orcid.org/0000-0001-9969-8610, PMID:10689646]",
  "descendants": [],
  "hp": "HP:0032330",
  "name": "Increased urinary 11-deoxycorticosterone level",
  "parents": [
    "HP:0012029"
  ],
  "property_value": [
    "http://purl.org/dc/elements/1.1/date \"2019-02-18T13:52:04Z\" xsd:dateTime",
    "http://purl.org/dc/terms/creator https://orcid.org/0000-0002-0736-9199"
  ],
  "synonym": {}
}
```

**Comment by colleenXu** [comment]
Done: updated x-bte annotation has been tested and updated https://github.com/NCATS-Tangerine/translator-api-registry/commit/aaf06ce87ca4babaa9cff444ec370b2d00ea27ba, and SmartAPI registration has been refreshed

<details><summary>Example based on the opening post</summary>
<p>

send a POST request to the api-specific endpoint, BioThings HPO only. Like http://localhost:3000/v1/smartapi/a5b0ec6bfde5008984d4b6cde402d61f/query

Put this in the request body: it's querying with the same phenotype as the opening post, `HP:0032330` (Increased urinary 11-deoxycorticosterone level)


```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "categories": ["biolink:PhenotypicFeature"],
                    "ids": ["HP:0032330"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

There should be at least 2 edges, one to each of the expected genes: `NCBIGene:1586` (CYP17A1) and `NCBIGene:1584` (CYP11B1)

```
                "1d22473cad817bf732319d754ba10aa2": {
                    "predicate": "biolink:condition_associated_with_gene",
                    "subject": "HP:0032330",
                    "object": "NCBIGene:1586",
                    "attributes": [],
                    "sources": [
                        {
                            "resource_id": "infores:hpo-annotations",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-hpo",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:hpo-annotations"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-hpo"
                            ]
                        }
                    ]
                },
                "2dd60f6669fdfc70f6df0c2b697fdcdd": {
                    "predicate": "biolink:condition_associated_with_gene",
                    "subject": "HP:0032330",
                    "object": "NCBIGene:1584",
                    "attributes": [],
                    "sources": [
                        {
                            "resource_id": "infores:hpo-annotations",
                            "resource_role": "primary_knowledge_source"
                        },
                        {
                            "resource_id": "infores:biothings-hpo",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:hpo-annotations"
                            ]
                        },
                        {
                            "resource_id": "infores:service-provider-trapi",
                            "resource_role": "aggregator_knowledge_source",
                            "upstream_resource_ids": [
                                "infores:biothings-hpo"
                            ]
                        }
                    ]
                }
            }
```

</p>
</details> 

---

#### And some notes

1. Based on the [source data info](https://hpo.jax.org/app/data/annotation-format), it seems like the gene-pheno annotations are based on disease-intermediates. I'd like to include those disease-intermediates (`annotations.disease_id` field) as an edge-attribute, but I didn't because: 
    - Not sure what biolink-term to use as the `attribute_type_id`
    - the field includes IDs from multiple namespaces: OMIM, ORPHA (it doesn't seem like there's more but I didn't double-check) 
    - may need post-processing because the biolink-model uses `orphanet` 
2. I also included an update to the superclass/subclass operations: now they work with ancestors/descendants rather than just parents/children. https://github.com/NCATS-Tangerine/translator-api-registry/commit/36e997552b054fbe6463a8efb9f4741e53e345e2

And a side-thing I noticed: two fields in the API that looked interesting but not usable as they are now:
- [xref.pmids](https://biothings.ncats.io/hpo/query?q=_exists_:xrefs.pmid): only a few records (2) have this field. also, this looks specific to the hpo term, rather than being a publication reference for an association. 
- [xrefs.mp](https://biothings.ncats.io/hpo/query?q=_exists_:xrefs.mp): only a few records (10) have this field. It seems like a connection between hp and mp terms would be useful...But maybe it'd be even better if hp / mp terms were grouped as the same entity (NodeNorm?) rather than connected with edges.
