### ISSUE TITLE
TRAPI validation error in meta_knowledge_graph in Dev and CI for TRAPI 1.5

### ISSUE THREAD

**Issue by maximusunc** [biothings/biothings_explorer#812]
Looks like there is a typo on one of the edges object. It's listed as follows:
```json
{
      "subject": "biolink:SequenceVariant",
      "predicate": "biolink:related_to",
      "object": "biolink:Disease\"",
      "knowledge_types": [
        "lookup"
      ]
}
```

**Comment by colleenXu** [comment]
@maximusunc

Thank you for finding this! This was a typo in our metadata that should have affected all instances. 

This should be fixed in <=10 min on your side. 

I've fixed the [typo](https://github.com/NCATS-Tangerine/translator-api-registry/commit/6954a2b414edfed27c870878cfd5bc92fe2bcd8d) and refreshed the [SmartAPI registration](https://smart-api.info/ui/09c8782d9f4027712e65b95424adba79) so it uses this fixed yaml.

**Comment by colleenXu** [comment]
I no longer see the issue in responses like https://bte.transltr.io/v1/meta_knowledge_graph. So I'm closing this issue.
