### ISSUE TITLE
Run all creative mode templates simultaneously / fix and adjust record-counting for queries and template execution

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#824]
As a likely improved alternative to https://github.com/biothings/biothings_explorer/issues/808, we should instead try running all templates simultaneously. 

This slightly complicates response merging, but race conditions should be solvable with a per-query execution lock.

More importantly, we still don't want to go over time, so we want to time out at about 4:55 to ensure there's time to finish up and make callbacks/store the response. This might be both on individual templates and on the entire handler.

After implementation, we'll want some performance testing to ensure this doesn't create unreasonable strain on memory/CPU.

**Comment by rjawesome** [comment]
See PRs

**Comment by rjawesome** [comment]
Note: It's likely that the current code for this PR will conflict with #825 because the code here aborts all subqueries when the time cap is reached. However, it is unclear how to handle this when the subqueries are in a queue seperate from the thread (and all subqueries from different queries are merged into one queue).

**Comment by tokebe** [comment]
Regarding integrating with #825, in that case we don't want to abort subqueries because we'd prefer them to keep running and cache results whether those results are being used immediately or not. So, if a template adds subqueries to the queue, and then the template execution is aborted, we'd want those subqueries to keep running -- it increases the chances the template will complete before timeout in subsequent queries to BTE.

**Comment by tokebe** [comment]
This being the case, after you've verified #825 performs well under high traffic, you might want to rebase branches addressing #825 to branches for this issue, so you can seamlessly merge the behavior of the two issues. Normally we wouldn't do this, but because both are very involved changes that will be going up simultaneously (and theoretically support one another, performance-wise), it makes sense to do so.

**Comment by tokebe** [comment]
@rjawesome please update PRs to merge in Pathfinder behavior from main (currently has a merge conflict, may require extra changes)

**Comment by rjawesome** [comment]
@tokebe done.

**Comment by colleenXu** [comment]
Fixes/logging-improvements were deployed to CI using commits to main branches:
* [query-handler](https://github.com/biothings/bte_trapi_query_graph_handler/commits/main/) 10/16-10/17 from Jackson
* https://github.com/biothings/call-apis.js/commit/7eb5892706733832041b99405765aa06368f770b

---

Related: changed per-query/per-template record max. Functionally increased max from 50k to 75k. 
https://github.com/biothings/call-apis.js/commit/501df367bd0687029be048362dacd23a2669d8b7

**Comment by colleenXu** [comment]
After discussing urgent timeout / "large response" problems with @tokebe, we decided on the following quick-changes to this feature (**not extensively tested**):
* Parallel template execution only: stop/terminate earlier (4:30 rather than 4:45)
* Drop record limit closer to what it was before/same as before (50k)

Note: large response maybe related to duplicated edge-attribute sets #891, but not sure. 

We can walk some of these changes back later after figuring out they're okay.

**Comment by colleenXu** [comment]
Commits:
* terminate at 4:30: https://github.com/biothings/bte_trapi_query_graph_handler/commit/9eabfa1af16c36ac6d97ec18ba841f43424fead5
* record max 55k: https://github.com/biothings/call-apis.js/commit/1924a11c28fd5f21984290e19d0c6214868c7946

**Comment by tokebe** [comment]
Related changes deployed to Prod as of 11/13
